version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task5
    expose:
      - "5252"
    # Supprimer toute dépendance au front-end
    # depends_on:
    #   - front-end

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task5
    expose:
      - "9000"
    # Supprimer toute dépendance au back-end
    # depends_on:
    #   - back-end

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task5
    ports:
      - "80:80"
    depends_on:
      - front-end
      - back-end

